# Generated by Django 5.1.2 on 2024-10-25 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_atividades_usuario_alter_atividades_disciplina_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_de_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data de registro')),
            ],
        ),
        migrations.CreateModel(
            name='ApoioEfetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carga_horaria_min', models.IntegerField()),
                ('carga_horaria_max', models.IntegerField()),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.atividade')),
            ],
        ),
        migrations.CreateModel(
            name='OrientacaoAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carga_horaria_min', models.IntegerField()),
                ('carga_horaria_max', models.IntegerField()),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.atividade')),
            ],
        ),
        migrations.CreateModel(
            name='TipoEnsino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ensino', models.CharField(choices=[('graduacao', 'Graduação'), ('pos_graduacao', 'Pós-Graduação'), ('pesquisa', 'Pesquisa')], max_length=50)),
                ('carga_horaria_min', models.IntegerField()),
                ('carga_horaria_max', models.IntegerField()),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.atividade')),
            ],
        ),
    ]
