# Generated by Django 5.1.2 on 2024-10-25 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_atividade_apoioefetivo_orientacaoacademica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso_pesquisa', models.CharField(max_length=100)),
                ('eventos_pesquisa', models.CharField(max_length=100)),
                ('orientacao', models.CharField(max_length=100)),
                ('carga_horaria_min', models.PositiveIntegerField()),
                ('carga_horaria_max', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='orientacaoacademica',
            name='atividade',
        ),
        migrations.RemoveField(
            model_name='tipoensino',
            name='carga_horaria_max',
        ),
        migrations.RemoveField(
            model_name='tipoensino',
            name='carga_horaria_min',
        ),
        migrations.RemoveField(
            model_name='tipoensino',
            name='tipo_ensino',
        ),
        migrations.AddField(
            model_name='tipoensino',
            name='nome',
            field=models.CharField(default='Tipo padrão', max_length=100),
        ),
        migrations.AlterField(
            model_name='tipoensino',
            name='atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_ensino', to='gestao.atividade'),
        ),
        migrations.CreateModel(
            name='Graducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala', models.BooleanField(default=False)),
                ('turma', models.BooleanField(default=False)),
                ('horario', models.BooleanField(default=False)),
                ('carga_horaria_min', models.PositiveIntegerField()),
                ('carga_horaria_max', models.PositiveIntegerField()),
                ('tipo_ensino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduacao_opcoes', to='gestao.tipoensino')),
            ],
        ),
        migrations.CreateModel(
            name='PosGraduacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade_mestrado', models.BooleanField(default=False)),
                ('aula_mestrado', models.BooleanField(default=False)),
                ('carga_horaria_min', models.PositiveIntegerField()),
                ('carga_horaria_max', models.PositiveIntegerField()),
                ('tipo_ensino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_graduacao_opcoes', to='gestao.tipoensino')),
            ],
        ),
        migrations.DeleteModel(
            name='ApoioEfetivo',
        ),
        migrations.DeleteModel(
            name='OrientacaoAcademica',
        ),
    ]
