# Generated by Django 5.1.2 on 2024-11-03 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0006_remove_atividades_disciplina_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graducao',
            old_name='horario',
            new_name='aula',
        ),
        migrations.RenameField(
            model_name='graducao',
            old_name='sala',
            new_name='monitoria',
        ),
        migrations.RenameField(
            model_name='graducao',
            old_name='turma',
            new_name='orientacao',
        ),
    ]
