# Generated by Django 5.1.2 on 2024-11-26 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0009_alter_graducao_carga_horaria_max_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ministra',
        ),
    ]
